# Generated by Django 4.0.2 on 2022-04-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_aria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
